project:
  type: website
  output-dir: docs

website:
  title: "Antony Barja"
  description: "I am an Spatial Data Scientistic in development, working in infeccios diseases spatial modeling , spatial statistic and geovisualization inside Health Innovation Lab - Cayetano Heredia Peruvian, Lima-Peru. My primary research involves of the spatial data analysis and spatial - temporal modeling, addition the use different thecnology of geographic Information of open source and free. Please, feel free to browse my personal website and If you wish you can leave a comment."
  site-url: https://ambarja.github.io/
  repo-url: https://github.com/ambarja/ambarja.github.io
  #google-analytics: "G-ZVPYZZSZ1B"
  repo-actions: [edit, issue]
  open-graph: true
  favicon: data/images/logo.png
  twitter-card:
    creator: "@antony_barja"
    card-style: summary
  navbar:
    right:
      - text: "About me"
        href: data/about/about.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Projects"
        href: blog.qmd  
      - text: "Videos"
        href: blog.qmd
      - text: "Course"
        href: blog.qmd
      - text: "Services"
        href: blog.qmd  
      - text: "CV"
        href: blog.qmd
      - text: "Geoviz"
        href: data/gallery/index.qmd

  page-footer:
    left: "© 2022 Antony Barja"
    right: |
      Made with ♥ using `{Quarto}`
    center: |
      
      <center>
# citation: true
# license: "CC BY"
format:
  html:
    theme:
      light: css/karat_quarto.scss
    css: css/karat.css
    include-after-body: footer.html
freeze: true