on:
  push:
    branches:
      - gh-pages

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Edited meta
        run: |
        description= "holiiiii"
        grep -o 'content="(ambarja)"' index.html | sed -i 's/content="(ambarja)"/$description/g' index.html
